[package]
name = "asjeeves-telemetry"
description = "Metrics, Logging and Tracing"
homepage = "https://github.com/Ameelio/asjeeves/"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Ameelio/asjeeves/"
version = "0.2.1"
edition = "2024"

[features]
error = []

axum = [
  "dep:axum"
]

bb8 = [
  "dep:bb8",
]

logger = [
  "dep:opentelemetry",
  "dep:opentelemetry-appender-tracing",
  "dep:opentelemetry-otlp",
  "dep:opentelemetry_sdk",
  "dep:tracing-opentelemetry",
  "dep:tracing-subscriber"
]

reqwest = [
  "dep:http",
  "dep:reqwest",
  "dep:reqwest-middleware",
  "dep:reqwest-tracing"
]

tower = [
  "dep:http-body",
  "dep:http",
  "dep:opentelemetry-semantic-conventions",
  "dep:tonic",
  "dep:tower-http",
  "dep:tracing-opentelemetry",
]

[dependencies]

# axum framework
axum = { workspace = true, optional = true }

# database metrics
bb8 = { workspace = true, optional = true }

# Add tracing to a service
http = { workspace = true, optional = true }
http-body = { version = "1.0.1", optional = true }
tower-http = { version = "0.6.8", features = ["trace"], optional = true}

# metrics
metrics.workspace = true

# otlp export for logger
opentelemetry = { version = "0.32.0", optional = true }
opentelemetry-otlp = { version = "0.32.0", features = ["grpc-tonic"], optional = true }
opentelemetry_sdk = { version = "0.32.1", features = ["rt-tokio"], optional = true }
tracing-opentelemetry = { version = "0.33.0", optional = true }
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json"], optional = true }
opentelemetry-appender-tracing = { version = "0.32.0", optional = true  }
opentelemetry-semantic-conventions = { version = "0.32.1", optional = true }

# regex for route snarfing
regex.workspace = true

# tracing for reqwest
reqwest = { workspace = true, optional = true }
reqwest-middleware = { workspace = true, optional = true }
reqwest-tracing = { workspace = true, optional = true }

# Error handling
thiserror.workspace = true

# grpc support
tonic = { workspace = true, optional = true }

# logging and collecting event metadata
tracing.workspace = true

# opentelemetry-http = "0.31.0"
# bytes = "1.11.1"
# http-body-util = "0.1.3"
