[package]
name = "asjeeves-encryption"
description = "Encryption and Key utilities."
edition = "2024"
homepage = "https://github.com/Ameelio/asjeeves/"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Ameelio/asjeeves/"
version = "0.1.0"

[dependencies]

# Deserialization
serde.workspace = true

# Ensure all bytes are zeroed when garbage collected.
zeroize.workspace = true

# #########################################################
# Key Encryption Key
# Algorithm: AES
# Can be deserialized from a base64 unpadded encoded string.
# #########################################################
aes-gcm.workspace = true
base64ct.workspace = true

# #########################################################
# Json Web Keys
# Algorithm: RSA, SHA 256
# #########################################################
json-web-key.workspace = true
json-web-tolkien.workspace = true
rsa.workspace = true
serde_json.workspace = true

# #########################################################
# Random Generation
# Algorithm: ChaCha 20, UUID V7
# #########################################################
rand_chacha.workspace = true
rand_core.workspace = true
uuid.workspace = true

# #########################################################
# Session Cookies
# #########################################################
cookie.workspace = true

# #########################################################
# Instrumentation & Errors
# #########################################################
thiserror.workspace = true
tracing.workspace = true
