[package]
name = "asjeeves-health-check"
description = "Basic HTTP Health Check Service"
edition = "2024"
homepage = "https://github.com/Ameelio/asjeeves/"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Ameelio/asjeeves/"
version = "0.2.1-alpha.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage,coverage_nightly)'] }

[dependencies]
bytes.workspace = true
http.workspace = true
http-body-util.workspace = true
tower.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"]}
tokio-test = "0.4.4"
