[package]
name = "asjeeves"
description = "A collection of utilities for Ameelio web services."
edition = "2024"
homepage = "https://github.com/Ameelio/asjeeves/"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/Ameelio/asjeeves/"
version = "0.1.2"

[features]
axum = [
  "dep:asjeeves-csrf",
  "dep:asjeeves-user-session",
  "telemetry",
  "asjeeves-telemetry/axum",
  "tower"
]

bb8 = [
  "telemetry",
  "asjeeves-telemetry/bb8"
]

dup_req_protection = [
  "dep:asjeeves-dup-req-protection"
]

encryption = [
  "dep:asjeeves-encryption",
]

logger = [
  "telemetry",
  "asjeeves-telemetry/logger"
]

reqwest = [
  "telemetry",
  "asjeeves-telemetry/reqwest"
]

telemetry = [
  "dep:asjeeves-telemetry",
]

tower = [
  "dep:asjeeves-health-check",
  "dep:asjeeves-jwks-service",
  "asjeeves-telemetry/tower",
  "telemetry"
]

zipstream = [ "dep:asjeeves-zipstream"]

[dependencies]
asjeeves-csrf = { version = "0.1.2", path = "../asjeeves-csrf", optional = true }
asjeeves-dup-req-protection = { version = "0.1.1", path = "../asjeeves-dup-req-protection", optional = true }
asjeeves-encryption = { version = "0.1.2", workspace = true, optional = true }
asjeeves-health-check = { version = "0.2.2", path = "../asjeeves-health-check", optional = true }
asjeeves-jwks-service = { version = "0.1.5", path = "../asjeeves-jwks-service", optional = true }
asjeeves-telemetry = { version = "0.2.0", path = "../asjeeves-telemetry", optional = true }
asjeeves-user-session = {version = "0.1.2",  path = "../asjeeves-user-session", optional = true }
asjeeves-zipstream = { version = "0.1.1", path = "../asjeeves-zipstream", optional = true }
