[package]
name = "asjeeves-dup-req-protection"
description = "Duplicate Request Protection"
edition = "2024"
homepage = "https://github.com/Ameelio/asjeeves/"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Ameelio/asjeeves/"
version = "0.1.2"

[dependencies]

redis.workspace = true
thiserror.workspace = true

[dev-dependencies]
redis-test = { version = "1.0.1", features = ["aio"] }
tokio = { version = "1", features = ["macros", "rt"]}
tokio-test = "0.4.4"

