name: Unit Tests

on:
  push:
    branches:
      - "main"
      - "release/**"
  pull_request:
    branches: 
      - "main"
      - "release/**"

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run Unit Tests
        run: cargo test
        env:
          TEST_REDIS_URL: redis://redis:6379
